#!/usr/bin/env bash

function help {
    echo "usage: $(basename $0) <mode> <component> [options]"
    echo ""
    echo "  Setup modules in the current environment."
    echo ""
    echo "Options:"
    echo "  -h, --help                      show usages and exit"
    echo "      --debug                     set debug mode on"
    echo "  -a, --all                       make the action for all components"
    echo ""
    echo "Modes:"
    echo "  update                          update components from environment"
    echo "  install                         install components from environment"
    echo "  purge                           uninstall components from environment"
    echo ""
    echo "Modules:"
    for module in $(getComponents $FILE_DIR)
    do
        echo "  $module"
    done
    exit 1
}

if [ -L ${BASH_SOURCE[0]} ]
then
	FILE_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd )"
else
	FILE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
fi

if ! [[ $LIB_DIR ]]
then
    export LIB_DIR=$FILE_DIR/../lib
fi

source $LIB_DIR/functions

MOD=""
setArgs ""
i=1
while((i <= $#))
do
    case ${!i} in
        -h | --help)
            if ! [[ $MOD ]]
            then
                help
            else
                addArgs "${!i}"
            fi
            ;;
        --debug)
            if ! [[ $MOD ]]
            then
                DEBUG=1
            else
                addArgs "${!i}"
            fi
            ;;
        -a | --all)
            ALL=1
            ;;
        update | install | purge)
            MODE=${!i}
            ;;
        *)
            if ! [[ $MOD ]]
            then
                MOD="${!i}"
            else
                addArgs "${!i}"
            fi
            ;;
    esac

    i=$(expr ${i} + 1)
done

if ! [[ $MODE ]]
then
    abort  "No mode specified!" 6
fi

if ! [[ $MOD ]]
then
    abort  "No module specified!" 6
else
    if ! [[ -e "$FILE_DIR/$MOD/$MODE" ]]
    then
        abort "Not supported $MODE mode for $MOD module!" 6
    else
        debug true
        $FILE_DIR/$MOD/$MODE $(args)
    fi
    exit $?
fi

if [[ $ALL ]]
then
    for module in $(getComponents $FILE_DIR)
    do
        $0 $module $MODE $(args)
    done
    exit $?
fi

debug false

help