#!/usr/bin/env bash

function help {
    echo "usage: $(basename $0) <mode> <component> [options]"
    echo ""
    echo "  Setup components in the current environment."
    echo ""
    echo "Options:"
    echo "  -h, --help                      show usages and exit"
    echo "      --debug                     set debug mode on"
    echo ""
    echo "Modes:"
    echo "  update                          update components from environment"
    echo "  install                         install components from environment"
    echo "  purge                           uninstall components from environment"
    echo ""
    echo "Components:"
    for component in $(getComponents $FILE_DIR)
    do
        echo "  $component"
    done
    exit $1
}

if [ -L ${BASH_SOURCE[0]} ]
then
	FILE_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd )"
else
	FILE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
fi

if ! [[ $LIB_DIR ]]
then
    export LIB_DIR=$FILE_DIR/lib
fi

source $LIB_DIR/functions

CMP=""
setArgs ""
i=1
while((i <= $#))
do
    case ${!i} in
        -h | --help)
            if ! [[ $CMP ]]
            then
                help
            else
                addArgs "${!i}"
            fi
            ;;
        --debug)
            if ! [[ $CMP ]]
            then
                DEBUG=1
            else
                addArgs "${!i}"
            fi
            ;;
        update | install | purge)
            MODE=${!i}
            ;;
        *)
            if ! [[ $CMP ]]
            then
                CMP="${!i}"
            else
                addArgs "${!i}"
            fi
            ;;
    esac

    i=$(expr ${i} + 1)
done

if ! [[ $MODE ]]
then
    abort  "No mode specified!" 6
fi

if ! [[ $CMP ]]
then
    abort  "No component specified!" 6
else
    debug true
    $FILE_DIR/$CMP/setup $MODE $(args)
    exit $?
fi

debug false

help