#!/usr/bin/env bash

sudo apt update
sudo apt install -y \
        sudo \
        htop \
        wget \
        curl \
        openssh-server \
        openssl \
        net-tools \
        dnsutils \
        iputils-ping

sudo apt clean -y
