#!/usr/bin/env bash

apt update
apt install -y \
        sudo \
        htop \
        wget \
        curl \
        openssh-server \
        openssl \
        net-tools \
        dnsutils \
        iputils-ping \
        sshfs

apt clean -y
