#!/usr/bin/env bash

function help {
    echo "usage: $(basename $0) <user> [options]"
    echo ""
    echo "  Install zsh in the user environment."
    echo ""
    echo "Options:"
    echo "  -h, --help                      show usages and exit"
    echo "      --debug                     set debug mode on"
    echo ""
    echo "Users:"
    for user in $(sync-ls "/environment/users")
    do
        echo "  $user"
    done
    exit 1
}

if [ -L ${BASH_SOURCE[0]} ]
then
	FILE_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd )"
else
	FILE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
fi

if ! [[ $LIB_DIR ]]
then
    export LIB_DIR=$FILE_DIR/../lib
fi

source $LIB_DIR/functions

OPTIONS=""
setArgs ""
i=1
while((i <= $#))
do
    case ${!i} in
        -h | --help)
            help
            ;;
        --debug)
            DEBUG=1
            OPTIONS="$OPTIONS${!i} "
            ;;
        *)
            addArgs "${!i}"
            ;;
    esac

    i=$(expr ${i} + 1)
done

if ! [[ $(args | wc -w) -eq 1 ]]
then
    abort "Missing arguments!" 6
fi

if ! [[ $(cat /etc/passwd | grep -e "^$(args 1)") ]]
then
    abort "User $(args 1) not exists!" 3
else
    user=$(args 1)

    debug true
    apt install i3 -y

    EV="\$HOME/.local/environment"
    I3="\$HOME/.local/i3"
    I3_CONFIG="\$HOME/.config/i3"

    su -l $user -c "$EV/exec sync-login"

    su -l $user -c "mkdir -p $I3 $I3_CONFIG"
    su -l $user -c "$EV/exec sync $I3 /environment/modules/i3"

    su -l $user -c "ln -sf $I3/X11/.xinitrc \$HOME/"

    exit 0
fi

debug false

help


