#!/usr/bin/env bash

apt update
apt install -y \
        git \
        vim \
        nano \
        ant \
        maven \
        gradle \
        nodejs \
        npm \
        openjdk-11-jdk

apt clean -y