#!/usr/bin/env bash
sudo apt update
sudo apt $1 -y \
        git \
        vim \
        nano \
        ant \
        maven \
        gradle \
        nodejs \
        npm \
        openjdk-11-jdk

sudo apt clean -y