#!/usr/bin/env bash

function help {
    echo "usage: $(basename $0) <user> [options]"
    echo ""
    echo "  Install zsh in the user environment."
    echo ""
    echo "Options:"
    echo "  -h, --help                      show usages and exit"
    echo "      --debug                     set debug mode on"
    echo ""
    echo "Users:"
    for user in $(sync-ls "/environment/users")
    do
        echo "  $user"
    done
    exit 1
}

if [ -L ${BASH_SOURCE[0]} ]
then
	FILE_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd )"
else
	FILE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
fi

if ! [[ $LIB_DIR ]]
then
    export LIB_DIR=$FILE_DIR/../lib
fi

source $LIB_DIR/functions

setArgs ""
i=1
while((i <= $#))
do
    case ${!i} in
        -h | --help)
            help
            ;;
        --debug)
            DEBUG=1
            ;;
        *)
            addArgs "${!i}"
            ;;
    esac

    i=$(expr ${i} + 1)
done

if ! [[ $(args | wc -w) -eq 1 ]]
then
    abort "Missing arguments!" 6
fi

if ! [[ $(cat /etc/passwd | grep -e "^$(args 1)") ]]
then
    abort "User $(args 1) not exists!" 3
else
    user=$(args 1)

    debug true
    apt install zsh -y

    EV="\$HOME/.local/environment"
    ZSH="\$HOME/.local/zsh"
    ZSH_CONFIG="\$HOME/.config/zsh"

    su -l $user -c "$EV/exec sync-login"

    su -l $user -c "mkdir -p $ZSH $ZSH_CONFIG"
    su -l $user -c "$EV/exec sync $ZSH /environment/modules/zsh"

    su -l $user -c "ln -sf $ZSH/.zshrc \$HOME/"

    chsh -s /bin/zsh $user

    su -l $user -c "git clone https://github.com/robbyrussell/oh-my-zsh.git $ZSH_CONFIG"
    su -l $user -c "wget https://raw.githubusercontent.com/KorvinSilver/blokkzh/master/blokkzh.zsh-theme -O $ZSH_CONFIG/themes/blokkzh.zsh-theme"
    exit 0
fi

debug false

help


