#!/usr/bin/env bash


function help {
    echo "usage: $(basename $0) <mode> [options]"
    echo ""
    echo "  Setup users in the current environment."
    echo ""
    echo "Options:"
    echo "  -h, --help                      show usages and exit"
    echo "      --debug                     set debug mode on"
    echo ""
    echo "Modes"
    echo "  update                          update components from environment"
    echo "  install                         install components from environment"
    echo "  purge                           uninstall components from environment"
    echo ""
    echo "Users:"
    for user in $(sync-ls "/environment/users")
    do
        echo "  $user"
    done
    exit 1
}

if [ -L ${BASH_SOURCE[0]} ]
then
	FILE_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd )"
else
	FILE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
fi

if ! [[ $LIB_DIR ]]
then
    export LIB_DIR=$FILE_DIR/../lib
fi

source $LIB_DIR/functions

CMD=""
setArgs ""
i=1
while((i <= $#))
do
    case ${!i} in
        -h | --help)
            if ! [[ $(args) ]]
            then
                help
            else
                addArgs "${!i}"
            fi
            ;;
        --debug)
            if ! [[ $(args) ]]
            then
                DEBUG=1
            else
                addArgs "${!i}"
            fi
            ;;
        update | install | purge)
            MODE=${!i}
            ;;
        *)
            addArgs "${!i}"
            ;;
    esac

    i=$(expr ${i} + 1)
done

debug true

if ! [[ $MODE ]]
then
    abort "Missing mode!" 6
else
     if ! [[ -e "$FILE_DIR/bin/$MODE" ]]
    then
        abort "Not supported $MODE mode!" 6
    else
        debug true
        $FILE_DIR/bin/$MODE $(args)
    fi
    exit $?
fi

debug false

help

