#!/usr/bin/env bash

wget https://mega.nz/linux/MEGAsync/xUbuntu_18.04/amd64/megacmd-xUbuntu_18.04_amd64.deb -O /tmp/sync.deb
#wget https://mega.nz/linux/MEGAsync/xUbuntu_18.04/amd64/megasync-xUbuntu_18.04_amd64.deb -O /tmp/sync.deb

dpkg -i /tmp/sync.deb

apt update
apt -f install -y

apt clean -y


